# Cross entropy cost function

##### Data
$$\{(x^{(i)}, y^{(i)}): i=1,\ldots,m\}$$

##### Model
$$
\begin{array}{lll}
p^{(i)}
&=&\mbox{softmax}(x^{(i)}W+b)\\
&=&e^{x^{(i)}W+b} / \mbox{np.sum}(e^{x^{(i)}W+b})
\end{array}
$$

##### Likelihood function
$$L(W,b)=\prod_{i=1}^m\prod_{k=0}^{9}\left(p^{(i)}[k]\right)^{y^{(i)}[k]}$$

##### Log-Likelihood function
$$l(W,b)=\sum_{i=1}^m\sum_{k=0}^{9} y^{(i)}[k]\log p^{(i)}[k]$$

##### Cost function
$$J(W,b)=-\frac{1}{m}\sum_{i=1}^m\sum_{k=0}^{9} y^{(i)}[k]\log p^{(i)}[k]$$

##### Maximum likelihood principle
$$\mbox{argmax}_{W,b}\ L\quad\Leftrightarrow\quad\mbox{argmax}_{W,b}\ l\quad\Leftrightarrow\quad\mbox{argmin}_{W,b}\ J$$

In [2]:
import tensorflow as tf

logits = tf.constant([[0.0, -0.1, 1.2], [0.0, 0.1, -1.2]])
y_true = tf.constant([[0.0,  0.0, 1.0], [0.0, 1.0,  0.0]]) 

probs = tf.nn.softmax(logits)
probs2 = tf.exp(logits) / tf.reshape(tf.reduce_sum(tf.exp(logits), axis=1), shape=(2,1))

cross_entropy = tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,
                                                           labels=y_true)
cross_entropy2 = - tf.reduce_sum(y_true * tf.log(probs), axis=1)

loss = tf.reduce_mean(cross_entropy)

with tf.Session() as sess:
    print("logits : ")
    print(sess.run(logits))
    print()
    
    print("probs  : ")
    print(sess.run(probs))
    print()
    
    print("probs2 : ")
    print(sess.run(probs2))
    print()
    
    print("cross_entropy  : ", sess.run(cross_entropy))
    print("cross_entropy2 : ", sess.run(cross_entropy2))
    print()
    
    print("loss  : ", sess.run(loss))

logits : 
[[ 0.  -0.1  1.2]
 [ 0.   0.1 -1.2]]

probs  : 
[[0.19138922 0.17317612 0.6354346 ]
 [0.41556454 0.45926985 0.12516563]]

probs2 : 
[[0.19138922 0.17317614 0.6354346 ]
 [0.41556454 0.45926985 0.12516563]]

cross_entropy  :  [0.45344603 0.7781173 ]
cross_entropy2 :  [0.45344606 0.77811736]

loss  :  0.61578166
