[khanacademy](https://www.khanacademy.org/math/ap-statistics/gathering-data-ap/sampling-methods/v/techniques-for-generating-a-simple-random-sample?modal=1)

<div align="center"><img src="img/Screen Shot 2019-08-13 at 11.06.01 AM.png" width="100%" height="30%"></div>

In [10]:
import numpy as np
import scipy.stats as stats
import random

print(np.random.normal(size=(2,3)))
print(stats.norm.rvs(size=(2,3)))
print(random.gauss(0,1))

[[ 0.25077014 -2.85668124  0.38102243]
 [ 1.66073638 -0.79028141 -2.06996645]]
[[ 0.07993134 -1.12416339 -0.28961701]
 [-0.37046242 -0.51843836  1.08527389]]
-0.7432394926599724


In [18]:
import random
import numpy as np

if 1:
    A = ['N', 'E', 'W', 'S']
elif 1:
    A = [[0,1], [1,0], [-1,0], [0,-1]]

print(random.choice(A))
print(np.random.choice(A, p=[0.1,0.1,0.1,0.7]))

N
E


In [21]:
import random
A = ['N', 'E', 'W', 'S']
print(random.sample(A,2))

['N', 'S']
